### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`

### ISSUE THREAD

**Issue by iloveyouso** [jsll/position-contrained-6dof-graspnet#1]
Hello, I'm trying to reproduce your code, but at train.py, it doesn't work.

**Configuration:** 
- RTX 3090
- ubuntu 18.04
- conda 24.1.1
- python 3.6.15
- torch1.4.0+cu100, torch vision 0.5.0+cu100
- cudatoolkit 10.0.130
- cudnn 7.6.5.32

But I keep giving me this error below:

`(kcc2) bjkim@hinton:~/anaconda3/Codes/kcc/position-contrained-6dof-graspnet$ python3 train.py -d /data/bjkim/kcc/full_dataset/ --gpu_ids 1
------------ Options -------------
batch_size: 64
beta1: 0.9
caching: False
checkpoints_dir: ./checkpoints
continue_train: False
dataset_root_folder: /data/bjkim/kcc/full_dataset/
dataset_split_ratio: [0.8, 0.15, 0.05]
epoch_count: 1
extra_name: 
gpu_ids: [1]
grasps_folder_name: grasps
init_gain: 0.02
init_type: normal
is_train: True
kl_loss_weight: 0.01
latent_size: 2
lr: 0.0002
lr_decay_iters: 50
lr_policy: lambda
manual_seed: 3709
model_scale: 1
niter: 100
niter_decay: 2000
no_vis: False
num_grasps_per_object: 64
num_objects_per_batch: 1
num_threads: 5
pointnet_nclusters: 128
pointnet_radius: 0.02
print_freq: 100
run_test_freq: 1
save_epoch_freq: 1
save_latest_freq: 250
serial_batches: False
validate: False
verbose_plot: False
which_epoch: latest
-------------- End ----------------
Directory ./checkpoints/vae_lr_0002_bs_64_scale_1_npoints_128_radius_02_latent_size_2 already exists and you have not chosen to continue to train.
Do you want to override that training instance with a new one the press (Y/N).
y
Overriding directory ./checkpoints/vae_lr_0002_bs_64_scale_1_npoints_128_radius_02_latent_size_2
#train images = 6318
#test images = 1185
Traceback (most recent call last):
  File "train.py", line 86, in <module>
    main()
  File "train.py", line 46, in main
    model.optimize_parameters()
  File "/home/bjkim/anaconda3/Codes/kcc/position-contrained-6dof-graspnet/models/grasp_net.py", line 86, in optimize_parameters
    out = self.forward()
  File "/home/bjkim/anaconda3/Codes/kcc/position-contrained-6dof-graspnet/models/grasp_net.py", line 67, in forward
    return self.net(self.pcs, self.grasps, self.features, train=self.is_train)
  File "/home/bjkim/anaconda3/envs/kcc2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bjkim/anaconda3/envs/kcc2/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/bjkim/anaconda3/envs/kcc2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bjkim/anaconda3/Codes/kcc/position-contrained-6dof-graspnet/models/networks.py", line 192, in forward
    return self.forward_train(pc, grasp, features)
  File "/home/bjkim/anaconda3/Codes/kcc/position-contrained-6dof-graspnet/models/networks.py", line 197, in forward_train
    z = self.encode(pc, grasp, features)
  File "/home/bjkim/anaconda3/Codes/kcc/position-contrained-6dof-graspnet/models/networks.py", line 179, in encode
    pc_xyz, features = module(pc_xyz, features)
  File "/home/bjkim/anaconda3/envs/kcc2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bjkim/anaconda3/envs/kcc2/lib/python3.6/site-packages/pointnet2_ops/pointnet2_modules.py", line 66, in forward
    new_features = self.mlps[i](new_features)  # (B, mlp[-1], npoint, nsample)
  File "/home/bjkim/anaconda3/envs/kcc2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bjkim/anaconda3/envs/kcc2/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/bjkim/anaconda3/envs/kcc2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bjkim/anaconda3/envs/kcc2/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 107, in forward
    exponential_average_factor, self.eps)
  File "/home/bjkim/anaconda3/envs/kcc2/lib/python3.6/site-packages/torch/nn/functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`

I guess I tried enough solutions proposed by GPT and on the internet, but it hasn't resolved.
I tried already:
- make it sure that dataset is downloaded and well-located
- check version compatibility
- check GPU memory issue
- Uninstall and reinstall from the beginning

can you help me?

**Comment by jsll** [comment]
Hi,

I tested my code again on an NVIDIA GeForce RTX 2060 running Ubuntu 23 with cudatoolkit 11.7. It trains without problem. 

Have you ensured that your GPU is recognized by PyTorch and that it supports the CUDA version you're using. You can check this by running:

python
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))
This will verify if CUDA is available and print the name of the GPU detected by PyTorch.

If everything seems to be in order, then consider installing cudatoolkit 11.7

**Comment by iloveyouso** [comment]
Thank you for the kind answer. 

Thanks for your recommendation, but I already made it sure that CUDA is available, and GPU can be detected by Pytorch, as below:
<img width="309" alt="image" src="https://github.com/jsll/position-contrained-6dof-graspnet/assets/89577191/da05f9a7-5385-4945-abad-6105ad862f56">

I will try cudatoolkit 11.7 and add a comment.

**Comment by iloveyouso** [comment]
I tried cuda 10.0, 11.7, 12.3 and respectively with each compatible version of pytorch and python, but still not working. 

**Trying CUDA 11.7, while installing pytorch,**
<img width="682" alt="image" src="https://github.com/jsll/position-contrained-6dof-graspnet/assets/89577191/06da6154-4596-4b20-a799-65baac7f0604">

**While Trying CUDA 10.0, while execute "train.py"**
<img width="680" alt="image" src="https://github.com/jsll/position-contrained-6dof-graspnet/assets/89577191/6d048fa4-ccf3-41c5-bf62-329279bd759a">

**While Trying CUDA 12.3, while executing "train.py"**
<img width="625" alt="image" src="https://github.com/jsll/position-contrained-6dof-graspnet/assets/89577191/8754c4b8-740d-4691-80dc-5c449c62ae53">

**Comment by iloveyouso** [comment]
So I just want to try "test.py" with pre-trained model, it still gives me the error like below:

<img width="935" alt="image" src="https://github.com/jsll/position-contrained-6dof-graspnet/assets/89577191/1acafee4-2d7e-4f71-92ce-880619c4c17c">

Can you help me with this error?

**Comment by iloveyouso** [comment]
P.S.

 I put the pre-trained model(which was downloaded from your google drive) in the /checkpoints,
as below:

<img width="284" alt="image" src="https://github.com/jsll/position-contrained-6dof-graspnet/assets/89577191/41865e57-4bb5-46f8-99ef-781ac62c621b">
